### ISSUE TITLE
EasyB tests fail

### ISSUE THREAD

**Issue by Blodir** [Matoking/Ohtu-Hatut#20]
```
[java] FAILURE Scenarios run: 2, Failures: 2, Pending: 0, Time elapsed: 7.76 sec
     [java] 	scenario "user can create a new reference list with a valid name"
     [java] 	step WHEN "a valid name is given to the list" -- Unable to locate element with name: name
```

Looks like the name tag is missing from referencelist_new.html

**Comment by tuomokar** [comment]
Nah it's not that - Thymeleaf's `field` tag attaches the name attribute to the element as it is (along with other things).

At the moment the easyB tests are configured to start at port 8081, which doesn't work locally but with the other configurations set up by Matoking it works in Travis, which is more important. Locally you might want to comment the easyB tests out. Of course, it'd be nice to get them to work also locally  without any tricks, but Travis is more important, and with the limited time it's not sensible to really spend too much time on it.

If you want to run the easyB tests locally, you can change the port to 8080, start the app and then run the easyB tests.
